### ISSUE TITLE
custom alerts grouping

### ISSUE THREAD

**Issue by trigan-d** [cloudflare/unsee#107]
Hi. Thanks for the nice tool!
We (Upwork) have just one major problem with Unsee. 
In our AlertManager setup we are grouping the same alerts by different criteria in order to provide different email notifications. Specifically, we have a lot of microservices maintained by several teams. Every team maintains more than one service. Our alerts have both "service" and "team" labels. And AlertManager groups the alerts by service for daily email notification and groups the same alerts by team for weekly digest. So we have 2 nodes in our routing tree. 
But Unsee groups all alerts by team only! It seems to be the first group met in AlertManager response, and Unsee just uses it. It is not convenient for us. We'd rather prefer to have the alerts grouped by service in Unsee. But unfortunately this is not configurable at all. 
Have you ever considered storing all alerts received from AlertManager as a plain list without any grouping, and then allowing the user to define any "groupBy" condition he want? Perfectly if in UI directly, but in config file is OK too. It'd be just cool, at least for us.
Thanks in advance for any answer!

**Comment by prymitive** [comment]
An early unsee internal prototype was doing grouping on its own, but we decided to just use Alertmanager groups so that the structure from notifications reflected what you see on the dashboard. This way you didn't need to search for the alert on the dashboard and you have a single source of truth for grouping logic, so I'd rather avoid pushing more logic/config down to unsee layer.
But we do use more real-time notification services than email and it sounds like your case isn't covered well, so we should try to improve that. It seems that a good first step would be to look into supporting multiple routing trees and maybe allowing user to select one of them with a filter (e.g. `@tree=email-daily`). I'll look into that.

**Comment by trigan-d** [comment]
Thanks a lot! We'll be waiting for it.

**Comment by prymitive** [comment]
I looked into this a bit and it will require some bigger changes. I hope to get a PR working next week.

**Comment by prymitive** [comment]
There's a WIP [receiver branch](https://github.com/cloudflare/unsee/tree/receiver) which handles multiple receivers, it's incomplete but will show all alerts and you can pass `@receiver` filter, let me know if that helps with your issue @trigan-d

**Comment by trigan-d** [comment]
@prymitive , thanks a lot! It is completely OK for our needs! Now we are waiting for a release :)

**Comment by prymitive** [comment]
We're releasing it internally, I'll let it run for a few days to ensure there are no bugs and if all goes well I'll tag a new release next week.
