### ISSUE TITLE
can't build from master due to bindata_assetfs problem 

### ISSUE THREAD

**Issue by trigan-d** [cloudflare/unsee#114]
Cloned master. Trying "make run". Got:

go-bindata-assetfs  -prefix assets -nometadata assets/templates/... assets/static/...
make: go-bindata-assetfs: Command not found
Makefile:41: recipe for target 'bindata_assetfs.go' failed
make: *** [bindata_assetfs.go] Error 127

**Comment by prymitive** [comment]
Does `make` work? It looks like a missing dependency in `make run` target.

**Comment by trigan-d** [comment]
Nope, the same for "make"

**Comment by prymitive** [comment]
`make run` correctly depends on all targets used to install tools required for building unsee binary, including github.com/elazarl/go-bindata-assetfs/, this might be an issue with your `$PATH` or some other weird local problem since I can't reproduce it.

github.com/elazarl/go-bindata-assetfs is needed for building and it seems that when Makefile installs it the binary doesn't end up in the `$PATH`, verify that you have it installed.

If you just want to try unsee from master than you can use docker, see [docs](https://github.com/cloudflare/unsee#docker)

**Comment by trigan-d** [comment]
Yep, the problem was with my GO setup. How do you live with it, folks, it's a nightmare, not a language :)
