### ISSUE TITLE
Option to remove summary or description

### ISSUE THREAD

**Issue by byblakout** [cloudflare/unsee#169]
Hey there - thanks for `unsee`, just started using and it's great.

One question: is it possible to remove either alert `description` or `summary` from the dashboard? Would clear up a good amount of dashboard space. For our purposes we don't need both.

Thanks!

**Comment by prymitive** [comment]
I can add a user setting for collapsing and hiding annotations by default and UI element on the alert for expanding those if needed (like a `+` icon).

**Comment by peimanja** [comment]
+1

**Comment by byblakout** [comment]
that would be perfect

**Comment by prymitive** [comment]
> For our purposes we don't need both.

What levels of suppression would work best for you? Options I can name are:
1. have a UI setting toggle that by default hides all annotations with option to expand per alert
2. have a `ANNOTATIONS_LIMIT=N` that by default hides all but first N annotations (sorted by keys, with 0 as a possible value)
3. have a `STRIP_ANNOTATIONS=[list]` that strips away all annotations found on that list (similar to `STRIP_LABELS`
4. have a `ALLOW_ANNOTATIONS=[]` option that only allows annotations found on that list (reversed `STRIP_ANNOTATIONS`)
5. have a `SHOW_ANNOTATIONS=[list]` that shows by default all annotations found on that list while keeping others hidden
6. have a `HIDE_ANNOTATIONS=[list]` that shows by default all annotations except those found on that list

I feel that annotations story is a bit different than labels, `STRIP_LABELS` exists because some metrics have labels that are just useless to the person receiving the alert (like `instance=mesos task id` or some redundant labels), while annotations are fully controlled by the prometheus user, so they all should be valuable, it's just that they aren't always needed on a dashboard. That's why I'm leaning more on the idea of hiding them, with an option to show if user wants this, rather than stripping away.
I think that annotation keys are likely to be standardized within a team, so maybe a global option to elect one or more annotation keys are the ones that are displayed by default makes most sense, and that would be option nr 5. Would 5 & 6 work for you?

Note to self: if some users would want to hide all by default empty list would need to be passed, which won't work since empty list == empty string, that's same as not passing any envs. Adding a third option seems like overkill so maybe some special magic value like `SHOW_ANNOTATIONS=[]` would be best?

**Comment by byblakout** [comment]
5 and 6 definitely make sense.
(thumbsup)

`SHOW_ANNOTATIONS=['summary']` would be our use.

**Comment by byblakout** [comment]
Awesome - thank you!
